.TH "LPM-INIT" "1" "July 2024" "LPM@0.1.0" ""
.SH "NAME"
\fBlpm-init\fR - Create a package.toml file
.SS "Synopsis"
.P
.RS 2
.nf
lpm init

alias: create
.fi
.RE
.SS "Description"
.P
\fBlpm init\fR can be used to set up a new package.
.SS "Examples"
.P
Generate a plain old package.toml using legacy init:
.P
.RS 2
.nf
$ mkdir my-lpm-pkg && cd my-lpm-pkg
$ git init
$ lpm init
.fi
.RE
.P
Generate it without having it ask any questions:
.P
.RS 2
.nf
$ lpm init -y
.fi
.RE
.SS "Configuration"
.SS "\fByes\fR"
.RS 0
.IP \(bu 4
Default: null
.IP \(bu 4
Type: nil or boolean
.RE 0

.P
Automatically answer "yes" to any prompts that lpm might print on the command line.

