.TH "LPM-HELP" "1" "July 2024" "LPM@0.1.0" ""
.SH "NAME"
\fBlpm-help\fR - Get help on lpm
.SS "Synopsis"
.P
.RS 2
.nf
lpm help <term>

alias: hlep
.fi
.RE
.SS "Description"
.P
If supplied a topic, then show the appropriate documentation page.
.SS "Configuration"
.SS "\fBviewer\fR"
.RS 0
.IP \(bu 4
Default: "man" on Posix, "browser" on Windows
.IP \(bu 4
Type: string
.RE 0

.P
The program to use to view help content.
.P
Set to \fB"browser"\fR to view html help content in the default web browser.

